version: "3.9"
services:
  mongo:
    image: mongodb/mongodb-atlas-local:8.0.0
    container_name: de-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: mongosh --eval "try { rs.status() } catch(e) { rs.initiate({ _id: 'replicaset', members: [{ _id: 0, host: 'localhost:27017' }] }) }" --quiet
      interval: 10s
      timeout: 10s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: de-backend
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      MONGODB_URI: mongodb://mongo:27017/Dashboard-Database?replicaSet=replicaset&directConnection=true
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo-data:
